language: node_js

node_js:
  - "iojs"
  - "0.12"
  - "0.10"
  - "4.0"
  - "4.1"
  - "4.2"
  - "5.0"
  - "5.1"

services:
  - mongodb

before_script:
  - 'if [ "$MONGOOSE_VERSION" ]; then npm install mongoose@^$MONGOOSE_VERSION; fi'

env:
  - MONGOOSE_VERSION=4.0
  - MONGOOSE_VERSION=4.1
  - MONGOOSE_VERSION=5
